#!/bin/sh

usage() {
		echo "emacswindow [file]"
    echo "Run an emacs window."
    echo ""
    echo "	-h --help"
    echo "		This menu."
    echo "	-p --position LINE COL"
    echo "		Goto the position in the file."
    echo "	-e --eval exprs"
    echo "		Evaluate the expressions after finding the file and moving to position."
    echo ""
}

EVAL=""
LINE_EXPR="nil"
COL_EXPR="nil"
FILE=""
while [ "$1" != "" ]; do
    case "$1" in
        -h | --help)
            usage
            exit
            ;;
        -p | --position)
            LINE_EXPR="(goto-line $2)"
            COL_EXPR="(right-char (- $3 1))"
            shift 3
            ;;
        -e | --eval)
            EVAL="$2"
            shift 2
            ;;
        *)
            FILE="$1"
            shift 1
            ;;
    esac
done

emacsclient -c --frame-parameters='((name . "floating") (width . 130) (height . 40))' \
    --eval "(find-file \"$FILE\")" "(push (current-buffer) frame-kill-buffers)" \
    "$LINE_EXPR" "$COL_EXPR" "(progn $EVAL)"
