#! /bin/sh

if [ -t 0 ]; then #use $1 if running interacitive
    input="$1"
else              #else use stdin
    input="$(cat)"
fi

if [ -d "$input" ]; then 
    lsd "$input"
elif [ -f "$input" ]; then
    nvim "$input"
fi
