#!/bin/sh
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width   4
bspc config window_gap     6
bspc config single_monocle true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

#open notification daemon
dunst &

# Set the border colors.
bspc config normal_border_color  "$color1"
bspc config active_border_color  "$color2"
bspc config focused_border_color "$color15"

bspc config split_ratio        0.52
bspc config borderless_monocle true
bspc config gapless_monocle    true
bspc config ignore_ewmh_focus  true

bspc rule -a Gimp      state=floating
bspc rule -a Xdialog   state=floating
bspc rule -a kmines    state=floating
# bspc rule -a Chromium  desktop='^2'
bspc rule -a mplayer2  state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a mpv                 state=fullscreen
bspc rule -a "*:*:floating"      state=floating
bspc rule -a "*:*:Miny"          state=floating
bspc rule -a Gnome-mines         state=floating
bspc rule -a Emacs               state=tiled
bspc rule -a Evince              state=tiled
bspc rule -a Steam               desktop='^3' follow=off
bspc rule -a discord             desktop='^4' follow=off
bspc rule -a Pulseeffects        desktop='^5' follow=off
bspc rule -a easyeffects         desktop='^5' follow=off
bspc rule -a Carla2              desktop='^5' follow=off
bspc rule -a 'qBittorrentv4.2.5' desktop='^6' follow=off
bspc rule -a 'qBittorrent'       desktop='^6' follow=off
bspc rule -a 'qbittorrent'       desktop='^6' follow=off
bspc rule -a transmission-gtk    desktop='^6' follow=off
