#!/bin/sh

if [ -t 0 ]; then #use $1 if running interacitive
    input="$1"
else              #else use stdin
    input="$(cat)"
fi

if [ "$input" = "" ]; then
    ls
elif [ -d "$input" ]; then
    ls "$input"
elif [ -f "$input" ]; then
    less --quit-if-one-screen "$input"
else
    echo "File not found."
    exit 1
fi
