#!/bin/sh
set -ex
guix pull
echo "Pulled."
if [ "$(whoami)" = "root" ]; then
    guix system reconfigure /config/"$(cat /etc/hostname)"-system.scm
else
    guix home reconfigure /config/"$(cat /etc/hostname)"-"$(whoami)".scm
fi
