#!/bin/sh
set -ex
cd /config
./packages/update-discord-info.sh
git reset
git add packages/discord.scm
git commit -m "Bumps Discord version" || echo Up to date.
guix home reconfigure /config/"$(hostname)"-jack.scm
nohup discord 2>&1 > /dev/null &
