#!/bin/sh
set -ex
pkill Discord || true
cd ~/code/guix-discord/
./update-discord-info.sh
git reset
git add xyz/jackfaller/discord.scm
git commit -m "Bumps Discord version" || echo Up to date.
git push origin master
guix pull --select=guix-discord
guix home reconfigure /config/"$(hostname)"-jack.scm
nohup discord 2>&1 > /dev/null &
