#!/bin/sh

volume=$(pactl get-sink-volume @DEFAULT_SINK@ | grep '[0-9]*%' --only-matching | sed 's/%// ; 1q')
volume=$((volume / $1 * $1)) #round to nearest multiple
new_volume=$((volume + $1))

if [ "$new_volume" -ge "100" ]; then
	new_volume=100
elif [ "$new_volume" -le "0" ]; then
	new_volume=0
fi

pactl set-sink-mute @DEFAULT_SINK@ 0 && pactl set-sink-volume @DEFAULT_SINK@ "$new_volume"%
