(define-module (packages discord)
  #:use-module (gnu packages base)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages cups)
  #:use-module (gnu packages fontutils)
  #:use-module (gnu packages freedesktop)
  #:use-module (gnu packages gcc)
  #:use-module (gnu packages gl)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages gnome)
  #:use-module (gnu packages gtk)
  #:use-module (gnu packages kerberos)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages node)
  #:use-module (gnu packages nss)
  #:use-module (gnu packages pulseaudio)
  #:use-module (gnu packages video)
  #:use-module (gnu packages wget)
  #:use-module (gnu packages xdisorg)
  #:use-module (gnu packages xml)
  #:use-module (gnu packages xorg)
  #:use-module (guix download)
  #:use-module (guix gexp)
  #:use-module ((guix licenses) :prefix license:)
  #:use-module (guix packages)
  #:use-module (guix utils)
  #:use-module (ice-9 match)
  #:use-module (nonguix build-system chromium-binary)
  #:use-module ((nonguix licenses) :prefix license:))

;; Generated by `update-discord-info.sh`.
;; begin generated content
(define discord-version "1.0.141")
(define discord-hash "1qfd86ng80f7aiz4c5bvf83ax7fgxw30c4l7hzk570297gl87a2y")
(define discord-uri "https://stable.dl2.discordapp.net/distro/app/stable/linux/x64/1.0.141/full.distro")
(define stub-uri "https://cdn.discordapp.com/apps/linux/1.0.141/discord-1.0.141.tar.gz")
(define stub-hash "0wzl0vzysqbwdd7xhln8jgd39lc6n0wqqys2bn8lnmf3raaj2k48")
(define module-uris '("https://stable.dl2.discordapp.net/distro/app/stable/linux/x64/1.0.141/discord_desktop_core/1/full.distro" "https://stable.dl2.discordapp.net/distro/app/stable/linux/x64/1.0.141/discord_erlpack/1/full.distro" "https://stable.dl2.discordapp.net/distro/app/stable/linux/x64/1.0.141/discord_spellcheck/1/full.distro" "https://stable.dl2.discordapp.net/distro/app/stable/linux/x64/1.0.141/discord_utils/1/full.distro" "https://stable.dl2.discordapp.net/distro/app/stable/linux/x64/1.0.141/discord_voice/1/full.distro"))
(define module-hashes '("0x20y203nybfhdfrww8l642aar2vgx3py4vq11b56ci11d9qcw2c" "0ymnf9wc1y98yz9q0ssn9xgz6lgmkgyzq02m2dc6vbksgzbfmci2" "18dchjx5mhf6yai27zq2xwcb35qxi0mk51ngv7kskxb7blqy8m04" "0hsvaymq763bvbpimpflyqs95mc5bfxnzbsh1wfm5g32zjnfkica" "00vy71nw1v88zkkc839hddmc88jr1na8sln4lhly0bkpna60dbdz"))
(define module-names '("discord_desktop_core" "discord_erlpack" "discord_spellcheck" "discord_utils" "discord_voice"))
;; end generated content

(define discord-stub
  (origin (method url-fetch) (uri stub-uri) (sha256 (base32 stub-hash))))

;; This is a dummy package which fetches the modules Discord needs.
;; Each module has a source which is a Brotli compressed tar file.
;; Decompress each of those files, then recompress them as zip files which is
;; what the client expects.
(define discord-modules
  (package
    (name "discord-modules")
    (version discord-version)
    (source
     (file-union
      "modules"
      (map (lambda (name uri hash)
             (list
              (string-append name ".br")
              (origin (method url-fetch) (uri uri) (sha256 (base32 hash)))))
           module-names module-uris module-hashes)))
    (build-system (@ (guix build-system copy) copy-build-system))
    (arguments
     (list
      #:install-plan
      #~(map (lambda (name)
               (let ((f (string-append name ".zip"))) (list f f)))
             '#$module-names)
      #:phases
      (with-imported-modules '((guix build utils))
        #~(modify-phases %standard-phases
            (add-after 'unpack 'brotli-repack-to-zip
              (lambda* (#:key #:allow-other-keys)
                (use-modules (guix build utils))
                (for-each
                 (lambda (name)
                   (invoke
                    "sh" "-c"
                    (string-append
                     "brotli --decompress --stdout " name ".br"
                     " | tar x"
                     "; cd files"
                     "; 7z a ../" name ".zip *"
                     "; cd .."
                     "; rm -rf files")))
                 '#$module-names)))))))
    (native-inputs (list brotli tar 7zip))
    (synopsis "Discord modules")
    (description "Discord modules")
    (license (license:nonfree "https://discord.com/terms"))
    (home-page "https://discordapp.com")))

(define-public discord
  (package
   (name "discord")
   (version discord-version)
   (source
    (origin
      (method url-fetch)
      (uri discord-uri)
      (sha256
       (base32 discord-hash))))
   ;; Use this build system to set XDG_DATA_DIRS and other variables.
   (build-system chromium-binary-build-system)
   (arguments
    (list
     #:patchelf-plan
     #~`(("Discord") ("chrome_crashpad_handler") ("chrome-sandbox"))
     #:install-plan
     #~`(("." "opt/discord")
         (#$discord-modules "opt/discord/resources/bootstrap")
         ("discord.desktop" "/share/applications/")
         ("discord.sh" "bin/discord")
         ("discord.png" "share/icons/hicolor/256x256/apps/")
         ("discord.png" "share/pixmaps/"))
     #:phases
     (with-imported-modules '((guix build utils))
       #~(modify-phases %standard-phases
           (add-after 'unpack 'brotli-unpack
             (lambda* (#:key #:allow-other-keys)
               (use-modules (guix build utils))
               (invoke "sh" "-c" "brotli --decompress --stdout full.distro | tar x; mv files/* .")))
           (add-after 'binary-unpack 'setup-cwd
             (lambda* (#:key outputs #:allow-other-keys)
               (use-modules (guix build utils))
               (define output (assoc-ref outputs "out"))
               ;; Patch the desktop file from the stub installer.
               (define temp (mkdtemp "extract-result.XXXXXX"))
               (invoke "tar" "xzf" #$discord-stub "-C" temp "Discord/discord.desktop")
               (invoke "mv" (string-append temp "/Discord/discord.desktop") ".")
               (delete-file-recursively temp)
               (substitute* "discord.desktop"
                 (("Exec=.*$")
                  (string-append "Exec=" output "/bin/discord\n"))
                 (("Path=.*$")
                  (string-append "Path=" output "/opt/discord\n")))
               (with-output-to-file "discord.sh"
                 (lambda _
                   (define (line . args)
                     (display (apply string-append args)) (newline))
                   (line "#!/bin/sh")
                   (line "cd " output "/opt/discord")
                   (line "./Discord"
                         ;; Always use Ozone on Wayland, not sure if this is a good idea.
                         " ${WAYLAND_DISPLAY:+--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WebRTCPipeWireCapturer}"
                         " \"$@\"")))
               (for-each
                (lambda (f) (chmod f #o755))
                '("Discord" "chrome_crashpad_handler" "chrome-sandbox"
                  "discord.sh"))))))))
   (native-inputs (list brotli tar))
   (inputs (list ffmpeg
                 gdk-pixbuf
                 libappindicator
                 libdbusmenu
                 libglvnd
                 libxscrnsaver
                 util-linux
                 wayland
                 ;; Not sure if all of these are needed.
                 gzip
                 libsm
                 node
                 pipewire
                 pulseaudio
                 unzip
                 wget
                 xdg-utils))
   (synopsis "Discord chat client")
   (description "All-in-one cross-platform voice and text chat for gamers.")
   (license (license:nonfree "https://discord.com/terms"))
   (home-page "https://discordapp.com")))
discord
